# Generated by Django 5.2.6 on 2025-09-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_time', models.TimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(max_length=48, unique=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.clientlist')),
                ('services', models.ManyToManyField(to='core.service')),
            ],
            options={
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
    ]
