# Generated by Django 5.2.6 on 2025-10-07 13:57

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date', '-created_on'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='clientlist',
            options={'ordering': ['is_client', 'last_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_earliest',
            field=models.CharField(default='', help_text='Earliest time when booking can be scheduled', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_latest',
            field=models.CharField(default='-', help_text='Latest time when booking can be scheduled', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='access_token',
            field=models.CharField(help_text='Unique token for secure booking access and verification', max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True, help_text='Date for booking to be scheduled'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.OneToOneField(help_text='The client making this booking', on_delete=django.db.models.deletion.CASCADE, to='core.clientlist'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when booking record was created'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Whether this booking has been confirmed'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(help_text='Services included in this booking (at least one required)', to='core.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when booking was last modified'),
        ),
        migrations.AlterField(
            model_name='clientlist',
            name='email',
            field=models.EmailField(help_text='Unique email address for client contact', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='clientlist',
            name='first_name',
            field=models.CharField(help_text="Client's first name", max_length=200),
        ),
        migrations.AlterField(
            model_name='clientlist',
            name='is_client',
            field=models.BooleanField(default=False, help_text='True if confirmed client, False if just a lead'),
        ),
        migrations.AlterField(
            model_name='clientlist',
            name='last_name',
            field=models.CharField(help_text="Client's last name", max_length=200),
        ),
        migrations.AlterField(
            model_name='clientlist',
            name='linked_services',
            field=models.ManyToManyField(blank=True, help_text='Services associated with this client', to='core.service'),
        ),
        migrations.AlterField(
            model_name='clientlist',
            name='phone_number',
            field=models.CharField(help_text="Client's contact phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name='clientlist',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional link to Django User account for authentication', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=False, help_text='Whether this service is currently available for booking'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Detailed description of what the service includes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary for service previews and listings'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='placeholder', help_text='Service image stored in Cloudinary CDN', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(help_text='Unique name of the service offered', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of service name', max_length=200, unique=True),
        ),
    ]
