# Generated by Django 5.2.6 on 2025-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_booking_options_alter_clientlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(help_text='Date for booking to be scheduled'),
        ),
    ]
