# Generated by Django 5.2.6 on 2025-10-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_booking_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person submitting the contact form', max_length=100)),
                ('email', models.EmailField(help_text='Email address for response communication', max_length=254)),
                ('message', models.TextField(help_text='The message content (max 1000 characters)', max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was submitted')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the admin has read this message')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_on'],
            },
        ),
    ]
